require 'apipie_bindings/authenticators/basic_auth'
require 'apipie_bindings/authenticators/basic_auth_external'
require 'apipie_bindings/authenticators/credentials_legacy'
require 'apipie_bindings/authenticators/oauth'
require 'apipie_bindings/authenticators/negotiate'
require 'apipie_bindings/authenticators/token_auth'
